name: CombatLogger
version:  '${project.version}'
api-version: 1.13
author: BTPluginz
main: dev.pluginz.combatlogger.CombatLoggerPlugin

commands:
  combatlogger:
    description: Main command for CombatLogger plugin
    usage: /combatlogger help
    aliases: [cl]

permissions:
  combatlogger.start:
    description: Allows players to start combat for a specific player
    default: op
  combatlogger.stop:
    description: Allows players to stop combat for a specific player
    default: op
  combatlogger.list:
    description: Allows players to list all players currently in combat
    default: op
  combatlogger.settimer:
    description: Allows players to set the combat timer
    default: op
  combatlogger.reload:
    description: Allows Players to reload the config and allys
    default: op
  combatlogger.ally:
    description: Allows players to ally with other players
    default: true
  combatlogger.help:
    description: Allows Players to use the help command
    default: true
  combatlogger.info:
    description: Allows Players to use the info command
    default: true