name: Build

on:
  push:
    branches: [ "master","Version*" ]
  pull_request:
    branches: [ "master", "Version*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List contents of target directory
      run: ls target
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BTsCombatLogger
        path: target/BTsCombatLogger-*.jar
